### ISSUE TITLE
Why do Alert tags have so many fields?

### ISSUE THREAD

**Issue by CanuckMarc** [NubeIO/nubeio-rubix-lib-models-go#140]
Why do the Alert Tags have so many properties?  Are they actually used?  It looks like there might be some circular references going on here.  

If we are not currently using this tag structure, I would strongly suggest that we change this to be the standard Tag type struct that is used on Networks/Devices/Points. 

https://github.com/NubeIO/nubeio-rubix-lib-models-go/blob/master/model/tags.go

**Comment by RaiBnod** [comment]
@CanuckMarc there are two things in tags searching, let's take the following two examples:

- Search the network & return tags of that network
   - Model: https://github.com/NubeIO/nubeio-rubix-lib-models-go/blob/master/model/network.go#L37
   - API: https://github.com/NubeIO/rubix-os/blob/a04e4b143cd905c7eed49fffaf0161aea23fa08d/router/router.go#L372
- Search `network`, `devices`, `points`, `alerts`, etc. where `tag=<tag>`
   - Model: https://github.com/NubeIO/nubeio-rubix-lib-models-go/blob/master/model/tags.go#L3
   - API: https://github.com/NubeIO/rubix-os/blob/a04e4b143cd905c7eed49fffaf0161aea23fa08d/router/router.go#L475
   
These two scenarios explain why the tags are associated with those models. I don't believe we'll encounter a circular dependency error.

Let me know, if you are having the issue.
